# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad9f94ff720bf0fbbb03d4fca42f6c6e1e650b92d1187c8e7c3552c8d3fcaa9cdaf0d2f562f1e398ec24f21453f88e0f8e51f0aa137572597c2f19e1d62c2468

test:
  secret_key_base: 2146a5aac6d1c4443e94ad876ae2f842f3c9b2495ce54d57f33d1652611dfcb59c79fabdb4887cccd23aad9001f3753d9d7bcf9fcccc1878ad4320189f214694

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
